# Generated by Django 2.2.10 on 2020-06-16 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0004_testcase_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.FileField(upload_to=submissions.models.submission_directory_path)),
                ('time_required', models.FloatField(blank=True, null=True)),
                ('memory_required', models.IntegerField(blank=True, null=True)),
                ('language', models.SmallIntegerField(choices=[(1, 'C'), (2, 'CPP'), (3, 'JAVA'), (4, 'PYTHON')], default=2)),
                ('verdict', models.SmallIntegerField(choices=[(1, 'WRONG ANSWER'), (2, 'ACCEPTED'), (3, 'TLE'), (4, 'MLE'), (7, 'RUNTIME ERROR'), (5, 'RUNNING'), (6, 'IN QUEUE'), (8, 'COMPILATION ERROR')], default=6)),
                ('on_test_case', models.SmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.Problem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
