# Generated by Django 2.2.10 on 2020-06-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_testcase_description'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_output', models.FileField(upload_to='outputs/%Y/%m/%d/')),
                ('verdict', models.SmallIntegerField(choices=[(1, 'WRONG ANSWER'), (2, 'ACCEPTED'), (3, 'TLE'), (4, 'MLE'), (7, 'RUNTIME ERROR'), (5, 'RUNNING'), (6, 'IN QUEUE'), (8, 'COMPILATION ERROR')], default=6)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submssion_history', to='submissions.Submission')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_upon', to='problem.TestCase')),
            ],
        ),
    ]
