# Generated by Django 2.2.10 on 2020-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submissionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionhistory',
            name='user_output',
            field=models.FileField(upload_to=''),
        ),
    ]
