# Generated by Django 2.2 on 2020-04-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('language', models.SmallIntegerField(choices=[(1, 'C'), (2, 'CPP'), (3, 'JAVA'), (4, 'PYTHON')], default=2)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.Problem')),
            ],
        ),
    ]
