# Generated by Django 2.2.10 on 2020-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='output_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='judge_solution',
            field=models.FileField(blank=True, upload_to='judge_soln/%Y/%m/%d'),
        ),
    ]
