# Generated by Django 2.2 on 2020-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
