# Generated by Django 2.2.10 on 2020-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200615_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
