# Generated by Django 2.2 on 2020-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200430_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='memory_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='on_test_case',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_required',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.SmallIntegerField(choices=[(1, 'WRONG ANSWER'), (2, 'ACCEPTED'), (3, 'TLE'), (4, 'MLE'), (7, 'Runtime Error'), (5, 'RUNNING'), (6, 'IN QUEUE')], default=6),
        ),
    ]
